# Generated by Django 5.1.6 on 2026-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorebook',
            name='is_constant',
            field=models.BooleanField(default=False, help_text='If True, always injected into the prompt'),
        ),
        migrations.AddField(
            model_name='lorebook',
            name='priority',
            field=models.IntegerField(default=50, help_text='Priority for evaluating this lorebook rule'),
        ),
        migrations.AddField(
            model_name='session',
            name='crack_stage',
            field=models.IntegerField(default=0, help_text='World crack stage'),
        ),
        migrations.AddField(
            model_name='session',
            name='stress',
            field=models.IntegerField(default=0, help_text="User's stress level in the game"),
        ),
    ]
