# Generated by Django 5.1.6 on 2026-04-03 12:50

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RpgCharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.CharField(max_length=255)),
                ('emotion', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rpg_character_images',
            },
        ),
        migrations.CreateModel(
            name='RpgChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rpg_chat_logs',
            },
        ),
        migrations.CreateModel(
            name='RpgLorebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=255)),
                ('lorebook', models.TextField()),
                ('priority', models.IntegerField(default=50)),
                ('is_constant', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rpg_lorebooks',
            },
        ),
        migrations.CreateModel(
            name='RpgSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=255)),
                ('total_tokens', models.IntegerField(default=0)),
                ('status_window_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rpg_sessions',
            },
        ),
        migrations.CreateModel(
            name='RpgMessageEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('chunk_content', models.TextField()),
                ('chat_log', models.ForeignKey(db_column='chat_log_id', on_delete=django.db.models.deletion.CASCADE, to='roleplay.rpgchatlog')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='roleplay.rpgsession')),
            ],
            options={
                'db_table': 'rpg_message_embeddings',
            },
        ),
        migrations.CreateModel(
            name='RpgHyperMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_game_time', models.TimeField(blank=True, null=True)),
                ('in_game_date', models.DateField(blank=True, null=True)),
                ('location_transition', models.TextField(blank=True, null=True)),
                ('characters_present', models.JSONField(default=list)),
                ('context_overview', models.TextField(blank=True, null=True)),
                ('events', models.JSONField(default=list)),
                ('infos', models.JSONField(default=list)),
                ('emotional_dynamics', models.TextField(blank=True, null=True)),
                ('dialogues', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_msg', models.ForeignKey(db_column='last_msg_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roleplay.rpgchatlog')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='roleplay.rpgsession')),
            ],
            options={
                'db_table': 'rpg_hyper_memories',
            },
        ),
        migrations.AddField(
            model_name='rpgchatlog',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='roleplay.rpgsession'),
        ),
        migrations.CreateModel(
            name='RpgStoryProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField(default=1)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='roleplay.rpgsession')),
            ],
            options={
                'db_table': 'rpg_story_progress',
            },
        ),
    ]
