# Generated by Django 5.1.6 on 2026-04-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpgsession',
            name='crack_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rpgsession',
            name='stress',
            field=models.IntegerField(default=0),
        ),
    ]
